services:
    reverse-proxy:
        container_name: reverse-proxy
        environment:
            - D=$
            - USER_SERVICE_URL=http://user-service:3002
            - QUESTION_SERVICE_URL=http://question-service:3004
            - MATCHING_SERVICE_URL=http://matching-service:3006
            - RMQ_URL=http://rabbitmq:15672
            - DOMAIN_NAME=${DOMAIN_NAME}
            - VPS_SSL_CERT_FILE=${VPS_SSL_CERT_FILE}
            - VPS_SSL_KEY_FILE=${VPS_SSL_KEY_FILE}
            - VPS_SSL_CONFIG_FILE=${VPS_SSL_CONFIG_FILE}
            - VPS_SSL_DHPARAMS_FILE=${VPS_SSL_DHPARAMS_FILE}
        image: nginx:1.27.2-alpine
        ports:
            - 443:443
        restart: always
        volumes:
            - ./nginx/templates:/etc/nginx/templates
            - ${VPS_SSL_CERT_FILE}:/etc/nginx/ssl/server.crt
            - ${VPS_SSL_KEY_FILE}:/etc/nginx/ssl/server.key
            - ${VPS_SSL_CONFIG_FILE}:/etc/nginx/ssl/options-ssl-nginx.conf
            - ${VPS_SSL_DHPARAMS_FILE}:/etc/nginx/ssl/server-dhparams.pem
        networks:
            - backend-network
        depends_on:
            - user-service
            - question-service
            - matching-service
        command: sh -c "envsubst < /etc/nginx/templates/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"

    matching-service:
        container_name: matching-service
        image: glemenneo/cs3219-ay2425s1-project-g31-matching-service:latest
        environment:
            - NODE_ENV=development
            - PORT=3006
            - DB_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@matching-db:27017/matching-service?authSource=admin
            - ACCESS_TOKEN_PUBLIC_KEY=${ACCESS_TOKEN_PUBLIC_KEY}
            - ACCESS_TOKEN_PRIVATE_KEY=${ACCESS_TOKEN_PRIVATE_KEY}
            - USER_SERVICE_URL=http://user-service:3002
            - QUESTION_SERVICE_URL=http://question-service:3004
            - RMQ_USER=${RMQ_USER}
            - RMQ_PASSWORD=${RMQ_PASSWORD}
            - RMQ_HOST=rabbitmq
        restart: always
        networks:
            - backend-network
        depends_on:
            - rabbitmq
            - matching-db

    rabbitmq:
        image: rabbitmq:4-management-alpine
        container_name: rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=${RMQ_USER}
            - RABBITMQ_DEFAULT_PASS=${RMQ_PASSWORD}
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq/
            - rabbitmq_log:/var/log/rabbitmq/
        networks:
            - backend-network

    matching-db:
        container_name: matching-db
        image: mongo:8.0.0
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
        ports:
            - '27067:27017'
        volumes:
            - 'matching_data:/data/db'
        networks:
            - backend-network
        command: mongod --quiet --logpath /dev/null --auth

    user-service:
        container_name: user-service
        image: glemenneo/cs3219-ay2425s1-project-g31-user-service:latest
        environment:
            - NODE_ENV=development
            - PORT=3002
            - DB_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@user-db:27017/user-service?authSource=admin
            - ACCESS_TOKEN_PUBLIC_KEY=${ACCESS_TOKEN_PUBLIC_KEY}
            - ACCESS_TOKEN_PRIVATE_KEY=${ACCESS_TOKEN_PRIVATE_KEY}
            - NODEMAILER_EMAIL=${NODEMAILER_EMAIL}
            - NODEMAILER_PASSWORD=${NODEMAILER_PASSWORD}
        restart: always
        networks:
            - backend-network
        depends_on:
            - user-db

    user-db:
        container_name: user-db
        image: mongo:8.0.0
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
        ports:
            - '27027:27017'
        volumes:
            - 'user_data:/data/db'
        networks:
            - backend-network
        command: mongod --quiet --logpath /dev/null --auth

    question-service:
        container_name: question-service
        image: glemenneo/cs3219-ay2425s1-project-g31-question-service:latest
        environment:
            - NODE_ENV=development
            - PORT=3004
            - DB_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@question-db:27017/question-service?authSource=admin
            - ACCESS_TOKEN_PUBLIC_KEY=${ACCESS_TOKEN_PUBLIC_KEY}
            - ACCESS_TOKEN_PRIVATE_KEY=${ACCESS_TOKEN_PRIVATE_KEY}
            - USER_SERVICE_URL=http://user-service:3002
        restart: always
        networks:
            - backend-network
        depends_on:
            - question-db

    question-db:
        container_name: question-db
        image: mongo:8.0.0
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
        ports:
            - '27047:27017'
        volumes:
            - 'question_data:/data/db'
            - ${VPS_SSL_CERT_FILE}:/etc/ssl/certs/mongodb.crt
            - ${VPS_SSL_KEY_FILE}:/etc/ssl/private/mongodb.key
        networks:
            - backend-network
        command: mongod --quiet --logpath /dev/null --auth

volumes:
    user_data:
    question_data:
    matching_data:
    rabbitmq_data:
    rabbitmq_log:

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
# without having to go through mapped ports
networks:
    backend-network:
